## 1.Python program to a Sort Matrix by index-value equality count

In [1]:
def get_idx_ele_count(row):

    # getting required count
    # element and index compared, if equal added
    # in list, length computed using len()
    return len([ele for idx, ele in enumerate(row) if ele == idx])


# initializing list
test_list = [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], 
             [6, 5, 4, 3, 2], [0, 5, 4, 2]]

# printing original list
print("The original list is : " + str(test_list))

# inplace sorting using sort()
test_list.sort(key=get_idx_ele_count)

# printing result
print("Sorted List : " + str(test_list))

The original list is : [[3, 1, 2, 5, 4], [0, 1, 2, 3, 4], [6, 5, 4, 3, 2], [0, 5, 4, 2]]
Sorted List : [[6, 5, 4, 3, 2], [0, 5, 4, 2], [3, 1, 2, 5, 4], [0, 1, 2, 3, 4]]


## 2.Python Program to Reverse Every Kth row in a Matrix

In [3]:
a = [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
k = 3

res = []

for i,ele in enumerate(a):

    if(i+1)%k==0:
        res.append(list(reversed(ele)))
                   
    else:
        res.append(ele)

print('Afer Reversing the Kth row: ' +  str(res))

Afer Reversing the Kth row: [[5, 3, 2], [8, 6, 3], [2, 5, 3], [3, 6], [3, 7, 4], [9, 2]]


In [7]:
a = [[5, 3, 2], [8, 6, 3], [3, 5, 2], [3, 6], [3, 7, 4], [2, 9]]
k = 3

res = [ele[::-1] if (i+1)%k ==0 else ele for i,ele in enumerate(a)  ]

print(str(res))



[[5, 3, 2], [8, 6, 3], [2, 5, 3], [3, 6], [3, 7, 4], [9, 2]]


## 3.Python Program to Convert String Matrix Representation to Matrix


In [18]:
test_str = "[gfg,is],[best,for],[all,geeks]"

rows = test_str[1:-1].split("],[")

mat = []
for row in rows:
    ele = row.split(",")
    mat.append(ele)

print(mat)

[['gfg', 'is'], ['best', 'for'], ['all', 'geeks']]


## 4.Count the frequency of matrix row length

In [33]:
test_list = [[6, 3, 1], [8, 9], [2],[10, 12, 7], [4, 11]]

print("The original list is : " + str(test_list))

res = dict()
for sub in test_list:

    if len(sub) not in res:
        res[len(sub)] = 1

    else:
        res[len(res)] += 1

print(res)

The original list is : [[6, 3, 1], [8, 9], [2], [10, 12, 7], [4, 11]]
{3: 3, 2: 1, 1: 1}


## 5.Convert Integer Matrix to String Matrix

In [40]:
test_list = [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]

print("The original list : " + str(test_list))

res = [[str(ele) for ele in sub]for sub in test_list]

print("The data type converted Matrix : " + str(res))

The original list : [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
The data type converted Matrix : [['4', '5', '7'], ['10', '8', '3'], ['19', '4', '6'], ['9', '3', '6']]


In [44]:
test_list = [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]

print("The original list : " + str(test_list))

sub_list = []
for sub in test_list:
    str_row = []
    
    for ele in sub:
        str_row.append(str(ele))
        
    sub_list.append(str_row)

print("The data type converted Matrix : " + str(sub_list))

The original list : [[4, 5, 7], [10, 8, 3], [19, 4, 6], [9, 3, 6]]
The data type converted Matrix : [['4', '5', '7'], ['10', '8', '3'], ['19', '4', '6'], ['9', '3', '6']]


## 6.Python Program to Convert Tuple Matrix to Tuple List

In [1]:
test_list = [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]

print("The original list is : " + str(test_list))

temp = [ele for sub in test_list for ele in sub]

res = list(zip(*temp))

print("The converted tuple list : " + str(res))


The original list is : [[(4, 5), (7, 8)], [(10, 13), (18, 17)], [(0, 4), (10, 1)]]
The converted tuple list : [(4, 7, 10, 18, 0, 10), (5, 8, 13, 17, 4, 1)]


## 7.Group Elements in Matrix

In [3]:
test_list = [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]

print("The original list is : " + str(test_list))

res = {idx[0]: [] for idx in test_list}

for idx in test_list:
    res[idx[0]].append(idx[1])
/
print("The Grouped Matrix : " + str(res))

The original list is : [[5, 8], [2, 0], [5, 4], [2, 3], [7, 9]]
The Grouped Matrix : {5: [8, 4], 2: [0, 3], 7: [9]}


## 8.Assigning Subsequent Rows to Matrix first rows element

In [4]:
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]

print('The Original list : ' + str(test_list))

res = {test_list[0][ele] :  test_list[ele + 1] for ele in range(len(test_list) - 1)}

print("The Assigned Matrix : " + str(res))

The Original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


## 9.Adding and Subtracting Matrices in Python

In [8]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print('Elemnts of first Matrix :')
print(A)

print('Elements of Second Matrix :')
print(B)

print('Sum of the matrices :')
print(np.add(A,B))

print('Subtration of the matrices :')
print(np.subtract(A,B))

Elemnts of first Matrix :
[[1 2]
 [3 4]]
Elements of Second Matrix :
[[5 6]
 [7 8]]
Sum of the matrices :
[[ 6  8]
 [10 12]]
Subtration of the matrices :
[[-4 -4]
 [-4 -4]]


## 10.Convert Matrix to Dictionary

In [13]:
li = [[5, 6, 7], [8, 3, 2], [8, 2, 1]]

res = {idx + 1: val for idx, val in enumerate(li)}

print(res)

{1: [5, 6, 7], 2: [8, 3, 2], 3: [8, 2, 1]}


## 11.Convert matrix to custom tuple matrix

In [20]:
test_list = [[4, 5, 6], [6, 7, 3], [1, 3, 4]]
print("The original list is : " + str(test_list))

add_list = ['Gfg', 'is', 'best']
res = []

for i in range(len(add_list)):
    for j in range(len(add_list)):
        res.append((add_list[i],test_list[i][j]))
    
res
# [('Gfg', 4), ('Gfg', 5), ('Gfg', 6), ('is', 6), ('is', 7), ('is', 3), ('best', 1), ('best', 3), ('best', 4)]

The original list is : [[4, 5, 6], [6, 7, 3], [1, 3, 4]]


[('Gfg', 4),
 ('Gfg', 5),
 ('Gfg', 6),
 ('is', 6),
 ('is', 7),
 ('is', 3),
 ('best', 1),
 ('best', 3),
 ('best', 4)]

## 12.Matrix Row subset

In [28]:
test_list = [[4, 5, 7], [2, 3, 4], [9, 8, 0]]
print("The original list is : " + str(test_list))

check_matr = [[2, 3], [1, 2], [9, 0]]

res = []

for x in check_matr:
    for y in test_list:
        if set(i).issubset(y):
            res.append(x)

res

The original list is : [[4, 5, 7], [2, 3, 4], [9, 8, 0]]


[[2, 3], [1, 2], [9, 0]]

## 13.Group similar element in matrix

In [32]:
from itertools import groupby
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]

print("The original list : " + str(test_list))

res =[]

for x,y in groupby(sorted(test_list)):
    res.append(list(y))

res

The original list : [1, 3, 5, 1, 3, 2, 5, 4, 2]


[[1, 1], [2, 2], [3, 3], [4], [5, 5]]

## 14.Row-wise tuple addition in tuple matrix

In [34]:
test_list = [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]

print("The original list is : " + str(test_list))
cus_eles = [6, 7, 8]
res = [[(idx+ (val,)) for idx in key] for key, val in zip(test_list, cus_eles)]

print("The matrix after row elements addition : " + str(res))

The original list is : [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
The matrix after row elements addition : [[('Gfg', 3, 6), ('is', 3, 6)], [('best', 1, 7)], [('for', 5, 8), ('geeks', 1, 8)]]


## 15.Create an n*n matrix, where all the sub-matrix have the sum of opposite corner elements as even

In [43]:
import itertools

def sub_mat_even(n):
    
    temp = itertools.count(1)

    l = [[next(temp)for i in range(n)]for i in range(n)]

    if n%2 == 0:
        for i in range(0,len(l)):
            if i%2 == 1:
                l[i][:] = l[i][::-1]
    
    for i in range(n):
        for j in range(n):
            print(l[i][j],end=" ")
        print()

n = 4
sub_mat_even(n)

1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 
